name:               "Leo's first blog"
description:        "I am a programmer"

url:                "https://sabb12.github.io/"
author:             "leo"
email:              ""
#gravatar_hash:      ""
#twitter:            ""
#email:              ""
#github:             ""
#pinterest:          ""
#linkedin:           ""
#facebook:           ""

disqus_shortname:   "sabb12-github-io"

background:         "data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wCEAAkGBxMTEhUTExMWFRUXGBgXGBcXFRoaGBgYFxcXFxcZGBgYHSggGBolHRcYIjEhJSkrLi4uFx8zODMtNygtLisBCgoKBQUFDgUFDisZExkrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrK//AABEIALcBEwMBIgACEQEDEQH/xAAaAAADAQEBAQAAAAAAAAAAAAAAAQIDBAUH/8QALxAAAQMCBQIGAgMBAAMAAAAAAQACESExA0FRYfBxgRKRobHB0eHxEyIyBEJSkv/EABQBAQAAAAAAAAAAAAAAAAAAAAD/xAAUEQEAAAAAAAAAAAAAAAAAAAAA/9oADAMBAAIRAxEAPwD5cqaJrkoA/O32VZOvYfaBz5IPPyo8Va1OQ0Ve2Z+ECjSvsEvXc2QTI0aFBMiTRuQ1QUa77m35SFempt5JRP8AZ1BkFJJcYH4CBl9YAk7/AEhwj/Rk6ZJueG0F8z9KMNk9NUBV1B+AmfC3c+iT8XJtki0Nq6+iA8LnVmB7KXYoFG+ef4TJLhJo3nmpDgP8jvmgBhZuptmh2Jk0R7puZAlx+yoOMchCA/jOfqm3DHX2VNbm4/lZPxXGgoEGrsRrRGeg+SsTjE0y0CX8cXK0acgICDP+MD/Vdh9qmyf8iOn2m+BudFk/FJQbUGcnmaxe5xvzNJrVtAAkoIawqneFu6zdjE7dFEIK/lOVOn2rYFDGrUu0pw6oJxX6KGsOieI+LeaG63QMt3p7oDJtHMkgO/NEOfkOd9EDcALlBxBp6qJi16JOHD5/KCji7j/5CFkQhB63AMhuUgdL5uyCRPbbM9UOOvZo+UDbnBpm74CZNK0b6lSRFXXyboh9P7Ovk37QBdm62QTI/wDJ3YcyQP8A2f2CgAvKAJLyniYgbRvcp4mIGiG9ys8LCmpoEDwsMuMmyWPjZCyMbGmgsnh4Qb/Z3YaoHhjwjxG+QWeGzxEudYXTq92yrEeB/UW90EYjpWmEwASVnhNkq/8AoKDHEdJV4OGs8NslbYxAEZ/CCMbEB+Fl4klTGSgMNkrTEdFAr/yN1zuN0EBUG7815qhU0IKY1ZYhkrUmiyPKoJ8KoHtznkpBVAoG1MuQI/Pl7VTdAmt6WQZQhxyTGY/ee6XiqgoWjzUqpJqco8ojrZKBzdABtzlad6xXllJVOvKCOe6CJQqgJoO8GsN7koc6KNqdU3w0eEVPypwwcqnM5BAE+Hd3t+UR4auq7T7Tc4NtU5n6U4WHP9jb3QUGT/ZxgcspxMaaNEDl0sV5cfhaNaGCc0EDDDauvopcS8wLeihoLytMXFgeFvc6oGXNZQVd6BYw55qjCwiSt3ODaC+qBYjg0QO5XOBJTK2wWILwxFVz4j5laY7p6LBwQa4AWWK6VqRDeqbcKIc6g90EYeDOy1kAUrzKfdQ95NxA016qHEoJe6VICqEQgQCsBDRznKqoQZ4tlktsY8iOZVWJ6oHHRBCvw055JRbnXtdAwOSoxL+q0LtuZLENpOU65oEVbW3J/dUmhVBiiBOMnz91TgJga0JvGUiSB0r1QP3PdSSebcKANzr8o5bkJlRCBndCRCaDtwcMuqaDVaOxREC3qVk57n7NCoYBdsEE4TPEYWmO8WFgh+KGiG9yuYEuKDbBbJS/6DJhXiHwNjMrLAzd5INMT+ogdyscLDLih1SulrIb1v8ASBOfSG0GZ1/C5y5aYtdgoACBYbS7pmuhppSyxLpoLaLQCAgxeVeBhzUqBhkldDnQIFs+oQQ91jHQH8rCfEZPPpJ7p58rQiBGqAe7z+FIZz7WkRUiuikt15dBKCqHmjwIJHKrQCtOdUmputzmfogwxsTL40U4QTLaHW/O6vCGaCXmqTUBp+VthYF/RBEUnmSgjcHzpST6+y3e8aeWXPlYGIETOc+nZAeHv8duXVRlt9JA/v7TxJitJQRkfrnIS8XI5KAO3nA8qpQNUA7zSVGNdZH5HKKCECQnHJQg9H+Yf+IhIgusk1oaJd2CyxccupYaINDhDN3YLbDhrZAg73WQaGCtXeyydiEoKLRMuMplxcYAoqbggVceybv+mLenXNBbMEMq6+nLLPFxZ6c9FkXkjlVTQ7IV16IIcU2rT+D/ANiB7+S2YwZDuUGeHhqsYgCPT5VYmOBap1y7LlxJJipO/wAINA/PTltVGI+fpTE9VrhYRPTKe3qgzwcOei28M1y5Huti0MaSSOkifu0+2a5jiU8VeR+fJA3a6WCg6oDbl3z5dU/XYSgWyTQn79+0Jg35HkgGn9puI0peBnXpVSxq0xW0HPbJBmWkUP3tcd0gNuddUEVy5l6KmuogGCPdTiP6wbbkfv1SeTQc59LMny55IHiOJO2lYqpNec0CBZO5/NEDjmvAk9hmd8xb8/SbTfpyyknzt+K8sgUajrkeeiRKOHyqgFAJ7RqkHd/gphyAD4yHcFCYaeBCDbEfJla4A8I8RHRZ4OHJ2F08fG0sLIJeZOpWohg1clgCB4j2WGI+Tqgb3lx1WuHg6lVh4YAkmFz42OXbDRBq7HYP8jxHeyQ/6HHbp+FzNauvAw/RBbSAJPWM9lk/GJ+L216qcbEJMTRQ0INGmtulbLXDwielhax3KeE0CpWWLjEnaedUG7S0RWeeqb8cVAEdL7Cfr9cgna32PyuhuGIk2yHwgyOHJv38/wALV2HAE+Xl+EPxjkPDFCb+qyBzqgt755QdB2USpLtuaI9/hBYcm1qrDC0Y3KvTogjwqzbpWazlf63Se8CdbxssMVxM389K1pyUCe+bRllmK05VUxpsQZrbUSTNbrNp6Re8eSH4kxGUHmWhQJ8x4jMSa5bgHO/qoc7baewHwfNDjXtSRfyzz0unh6m3qgRCXZamScpoAMq5EhQBntyyBSqDZ1P6/aZZ05dS4i99qe4QQTFO360U1or8dAK+GbTSdZtKisWtt8myBzSIHyVTTooaEwgYKFJdsPVCDsxsUAQ1Z4OHNTZX/E1v+jJ0CjFxJp6CyAx8WaDstMBgAkpYeGBV09FGNiz8bIJx8WTptooa1Vh4crpYwC/PwgWDg5oxMUW9VGLjTnTbvff7WJQMnm8q8ILNy3/52UlBWK7KuvnRY4grfRViOv36T8qGMJpy6DbCF3GvxO1oTJLiBwA/FU3iAApw68vKBPM9Mvypnn7TxLqS5AlrhNCzZ0WpMRqbffRBbnAXU4mNp1gxFtVk906V+NItlwqCCdye5JKBtfvEzavTpCTnEkm2d99UTS+99dNTXLTZTP11QM8qpCNk0AMuWstWxIm2fT5KgDT69+qJ5lsEC8cA26JOxOZRbNS+QemUUj5WfNEFvceWSDtL6yllnS2kdOqvpT3QZkFUB9zZWHEUmRJMXEkRPhNJjNMECxEmnYjWKIB2HFDRSYi/OFT18kyJkxQRbsOSgX8h2QlMaoQbCSVuC1m59lLBA5RYFxJQWXlxWrMHMlThs8Ik+SyxcUn6QdBx4oPOPZYOxSfnf5P6WRJK6MPDF0Esw5ur/jA/Hwh+Nk0Wg65TUdFiXG/ZB0ANzqb+6p5yyzjXL1WGF7ro8MRNzQT5dv2gzbhTU8laCG7npTzWTsXllLmGoIgikRvWUF+KZ39Fo4wDPZGC0Um1zWJ/MLIHxGTEU631FdfK1EET+0G8EQcwqfLjWth6bcomWhszent6IKw20k859pf6dXPrbJJz/FzmqC7fptqfZBLtKeY02z2Ul33058J4gihyMbdts+6zBKCo6G+YyjK4/aRKlCC2uiPOnKIGyW6e3ogUodiR0jrv2Tm9lLjNMgNbaxU9e5oglzvb5BQW6yKSARlSKnIjNQec1/KvDZXgQAKcSVM5qyR4bCZvUm2lhEXvVAnOtQjfXT2hSwpAWn0VOImgMTSdJzjPoglxSIjLom306SjxIF4TohHLIQdP/RiTVGCzMrLwyYWj3T/UWCB4r51n4+1iFo6+kcqk0IKwmrRzsrTRMNpae3wsXumqCXG6bdFEStsNoAk85RBrHhFlniPnpr8ZSliOJvlr7bfCpjOqAmdjX8rYYRAmD5KXYgbQ17rkc6TPMrnRBu58+VIt39VTTTYfZvv9rJg2RjPsMo9c79vhBT36UvmNlnMmedVM3+Oc9UNrFCefv0Qa4UZlAxJr2HlqkHkHMbi6UwIyvQCZO+nsgTiN/wA1tsmO2dcjaBtY/wD0s55yyAgc9kkAoQU1NRKCgbxTY19xXmaylaYoiRnSIII7rJA47rS2/LrNquROo2p9wgdIz8U2pEVzm/ZTFac8lIKZFMtq8hAgqKQTKAaSkQmASDsK7CQPchSgcISSQdAoN1Vh19E8Nn4PlzuoxCglb4eGdOFZYQW7z4RTPeo8tz6IFivBpFuEmFhEz3++dE/HE11HYiDVQCg1w3DIdDPxCHO0899VAdSJMaZSNR8qmNQWGjSPU725bqrfiFuVdsknOjr9X6rIxWoFo0Pe4QQ5yTAmDSgFPwMzvkkxBoXwNz5jnwsec9Fc58ul4Y53HWnugQPIn3tqtGDzupYBPI77KgZO0oKBGsXjqBagJrbqa0qsjOfAh7pMxGwEASk5yAQEkSgcpIJRKCwd0jpMGPhG6Hmwyoc4JqO/XqgzQAqATAQACTzkm5ymdUBG3TmabW0JkCMqya5QI3rCkuoBJIFtBOgyRKBgolEqUBCaCEkAShMuOp80kHU91Oc/ay8s8/pDyJOQnrTv2VMBueZfCDVkC453WZN03uy2zzWUoGU/Ck23IsrbPOdUDaFuxte8e2kLJo+oTxDSmsHv2iyCXSK+Vb+slt62WJ3VEzEmcjWt4itqRr8CZQAO3v8AaUpSqnVBRH5Ul+tchJ0EDyHsEOHJlQSgYVlyhqt1dr9PJApUpk6BJAISQUDThJCCi5IJNN9cuZ5+aAgZam6nfb2UudTk91ACCi6bqSUBOECVAJJoBIITa3b9C6ALuadFKAiUAmlCEG3hzypT46JuxKaJoQS3NSChCC2hahsn0/aEIHjGBQ88t1gXRncRT09vVCEEg1rzySlJCB+FV4kIQLEPfh1UkpIQUFTwhCCJSQhAyUIQgEkIQUTKCkhBKaEIEmbIQgEIQgEghCARKEIFKaEIP//Z"

paginate:           3
paginate_path:      "/page:num/"

baseurl:            ""
permalink:          /:year/:month/:day/:title/

markdown:           kramdown

nav:
  - name:           "About"
    href:           "/about"
  - name:           "TIL"
    href:           "/TIL"
  - name:           "post"
    href:           "/post"


sass:
  style:            :compressed

defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"
  -
    scope:
      path:         ""
      type:         "TIL"
    values:
      layout:       "TIL"


gems:
  - jekyll-paginate

plugins:
  - jekyll-sitemap